// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkzebjmgxoqnjulvmqta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxremViam1neG9xbmp1bHZtcXRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzgzMjIsImV4cCI6MjA3MTcxNDMyMn0.Cxx4o2B4mL85RXFMQvtL66YYwl7i8a9TGZPhIPSN1qA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});